### ISSUE TITLE
Issue after latest patch

### ISSUE THREAD

**Issue by EvergreenMoth8** [stiffmeds/Obeliskial-Options#1]
i am unsure what part of the mod is causing this but it only started doing this after the latest patch. i only have obeliskial and bepinex installed so i know its not from another mod. also this is in single player not multiplayer

![image](https://user-images.githubusercontent.com/48872529/229319994-74018be9-86bd-4b9d-a4a9-f7d3272ed70b.png)

**Comment by EvergreenMoth8** [comment]
i noticed the console gave me this error text before i closed the game

[Error  : Unity Log] MissingMethodException: Method not found: int .AtOManager.GetNgPlus()
Stack trace:
(wrapper dynamic-method) TownManager.DMD<TownManager::ShowButtons>(TownManager,bool)
TownUpgradeWindow.Show (System.Boolean state) (at <d1b46ed883cc4dca9c11c3a3bc5700f9>:0)
TownManager.ShowTownUpgrades (System.Boolean state, System.Boolean forceIt) (at <d1b46ed883cc4dca9c11c3a3bc5700f9>:0)
(wrapper dynamic-method) TownManager.DMD<TownManager::Start>(TownManager)

**Comment by stiffmeds** [comment]
Thanks; they changed how GetNgPlus works for this patch item:
- Fixed a problem when a user disconnected inside the Wolf Wars zone that didn't restore the Madness level after loading the game.

I've uploaded [a release that fixes this issue](https://github.com/stiffmeds/Obeliskial-Options/releases/).
