### ISSUE TITLE
"Overcharge[OC] X" or "Repeat Up to X" screen does not load

### ISSUE THREAD

**Issue by WeizheXu** [stiffmeds/Obeliskial-Options#2]
First of all, amazing mod! Just want to report a bit of a bug that triggers when using cards that let you select the number of uses such as overcharge or repeat up to x. The UI to select the number of uses won't appear and the game will freeze at that step as shown by the screenshot. I've tested that these cards work in Vannila and this is the only mod that I have. Also, the console says "Argument Null Exception: Value cannot be null". Details of the error message are also in the screenshot. Thanks in advance for the potential fix!
![image](https://user-images.githubusercontent.com/24322856/233336832-527fe9bf-1811-4b43-ad46-dc4496f7511f.png)

**Comment by stiffmeds** [comment]
Thanks for the bug report! I have [released a new version to fix this](https://github.com/stiffmeds/Obeliskial-Options/releases).
